[project]
name = "logcrawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prometheus-client>=0.23.1",
    "ruff>=0.14.0",
    "vaapi>=0.7.9",
]
